# Railway Build Configuration
[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && npm run start:prod"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
